login:
  user:                                        "input#username"
  pass:                                        "input[name=password]"
  submit:                                      "form div button[type='submit']"
  otp:                                         "input#code"

dashboard:
  panel:                                       "nav[aria-label='Navigation panel']"

table:
  main:                                        ".tab-clip > div:nth-child(6)"
  download-btn:                                "button#download"
  processing:                                  "div#CancelDialog-Dialog-Body-Id .cancelContainer"
  iframe:                                      "iframe[title]"
  category:                                    "#tab-dashboard-region > div:nth-child(8) .tabComboBoxNameContainer span"
  export:                                      "#viz-viewer-toolbar > div:last-child #download"
  dropdown:                                    "div.tileContainer"
  download:                                    "div[aria-labelledby='download']"
  download data:                               "div[aria-labelledby='download'] > div:nth-child(2) span:last-child"
  pop-up data:                                 "button[data-tb-test-id='download-data-Button']"
  info:                                        "div[aria-label='Alerts'] > div span"
  crosstab:                                    "div[aria-labelledby='download'] > div:nth-child(3) span:last-child"
  pop-up:                                      "div[aria-label='Download Crosstab']"
  dataIndex:                                   "div[aria-label='Single Sheet Selection'] > div[title='1.日报(当日)']"
  csv:                                         "div[aria-label='Download Crosstab'] .horizontal > label:last-child"
  btn:                                         "div[aria-label='Download Crosstab'] .low-density"
  data:                                        "div.tab-clip > div:nth-child(6)"
  index table:                                 "div[tb-test-id='1.日报(当日)'] .tab-clip-focusbox"
  date-1:                                      "#tabZoneId12 .QueryBox"
  date-2:                                      "#tabZoneId14 .QueryBox"
  date-s:                                      "input[class='QueryBox']"
  title:                                       "#tableauTabbedNavigation_tab_8"
  table data:                                  "div.tab-tvYLabel img"
  toolbar:                                     "div[role='toolbar']"
  tab:                                         "#tabZoneId12"
  tab-1:                                       "#tableauTabbedNavigation_tab_1"
  tab-2:                                       "#tableauTabbedNavigation_tab_2"
